[package]
authors = ["Suibeom <suibeom@gmail.com>"]
edition = "2018"
name = "softrender"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.*"
sdl2 = "0.34"
